# Generated by Django 5.0.1 on 2024-03-12 14:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baskets',
            fields=[
                ('basket_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('goods_name', models.CharField(blank=True, max_length=50, null=True)),
                ('goods_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('goods_count', models.IntegerField(default=0)),
                ('goods_id', models.IntegerField(blank=True, null=True)),
                ('billing_id_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Елементи замовлення',
                'verbose_name_plural': 'Елементи замовлення',
                'db_table': 'baskets',
            },
        ),
        migrations.CreateModel(
            name='Billings',
            fields=[
                ('billing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_phone', models.IntegerField(choices=[(0, 'Не активне'), (1, 'Не оформленно'), (2, 'Оформленно'), (3, 'Оплачено'), (4, 'Відправленно у доставку'), (5, 'Доставлено')], null=True, verbose_name='Статус Замовлення')),
                ('full_price', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('billing_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення замовлення')),
                ('billing_update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата оновлення замовлення')),
                ('billing_email', models.CharField(max_length=50, null=True, verbose_name='Email')),
                ('billing_first_name', models.CharField(max_length=50, null=True, verbose_name="Ім'я")),
                ('billing_second_name', models.CharField(max_length=50, null=True, verbose_name='Прізвище')),
                ('billing_phone_number', models.CharField(max_length=15, null=True, verbose_name='Номер телефону')),
                ('billing_address', models.CharField(max_length=100, null=True, verbose_name='Адреса Доставки')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'db_table': 'billings',
            },
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Назва сторінки')),
                ('page_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Посилання')),
                ('page_content', ckeditor.fields.RichTextField(blank=True, verbose_name='Вміст сторінки')),
                ('page_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='CEO')),
                ('page_status', models.BooleanField(default=True, verbose_name='Відображення сторінки')),
            ],
            options={
                'verbose_name': 'Сторінки',
                'verbose_name_plural': 'Сторінки',
            },
        ),
        migrations.CreateModel(
            name='PhoneCategoryModel',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Бренд')),
                ('cat_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Посилання')),
            ],
            options={
                'verbose_name': 'Категорії',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_cat_id', models.IntegerField(blank=True, choices=[], null=True)),
                ('phone_name', models.CharField(max_length=50, verbose_name='Назва')),
                ('phone_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Опис')),
                ('phone_price', models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name='Ціна')),
                ('phone_image', models.ImageField(blank=True, null=True, upload_to='phone_images/%Y/%mm/%d', verbose_name='Головне Зображення')),
                ('phone_additional_image_1', models.ImageField(blank=True, null=True, upload_to='phone_images/%Y/%mm/%d', verbose_name='Додаткове Зображення №1')),
                ('phone_additional_image_2', models.ImageField(blank=True, null=True, upload_to='phone_images/%Y/%mm/%d', verbose_name='Додаткове Зображення №2')),
                ('phone_additional_image_3', models.ImageField(blank=True, null=True, upload_to='phone_images/%Y/%mm/%d', verbose_name='Додаткове Зображення №3')),
                ('phone_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення')),
                ('phone_amount', models.IntegerField(null=True, verbose_name='Кількість на складі')),
            ],
            options={
                'verbose_name': 'Телефони',
                'verbose_name_plural': 'Телефони',
                'db_table': 'phones',
                'ordering': ['phone_id'],
            },
        ),
    ]
