# Generated by Django 5.0.1 on 2024-03-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='phonecategorymodel',
            table='phone_category',
        ),
    ]
