# Generated by Django 5.0.1 on 2024-01-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billings',
            name='status_phone',
            field=models.IntegerField(null=True, verbose_name='Статус Замовлення'),
        ),
    ]
