# Generated by Django 5.0.1 on 2024-01-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_billings_status_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billings',
            name='status_phone',
            field=models.IntegerField(choices=[('0', '0'), ('1', '1'), ('2', '2')], null=True, verbose_name='Статус Замовлення'),
        ),
    ]
