# Generated by Django 5.0.1 on 2024-01-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_alter_billings_status_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billings',
            name='status_phone',
            field=models.IntegerField(choices=[(0, 'Відсутнє'), (1, 'Не оформленно'), (2, 'Оформленно')], null=True, verbose_name='Статус Замовлення'),
        ),
    ]
