# Generated by Django 5.0.1 on 2024-01-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_alter_billings_status_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='phone_amount',
            field=models.IntegerField(null=True, verbose_name='Кількість на складі'),
        ),
        migrations.AlterField(
            model_name='billings',
            name='status_phone',
            field=models.IntegerField(choices=[(0, 'Не активне'), (1, 'Не оформленно'), (2, 'Оформленно')], null=True, verbose_name='Статус Замовлення'),
        ),
    ]
