# Generated by Django 5.0.1 on 2024-01-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_phonemodel_phone_amount_alter_billings_status_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='phone_additional_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='phone_images/%Y/%mm/%d', verbose_name='Додаткове Зображення №1'),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='phone_additional_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='phone_images/%Y/%mm/%d', verbose_name='Додаткове Зображення №2'),
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='phone_additional_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='phone_images/%Y/%mm/%d', verbose_name='Додаткове Зображення №3'),
        ),
        migrations.AlterField(
            model_name='billings',
            name='status_phone',
            field=models.IntegerField(choices=[(0, 'Не активне'), (1, 'Не оформленно'), (2, 'Оформленно'), (3, 'Оплачено'), (4, 'Відправленно у доставку'), (5, 'Доставлено')], null=True, verbose_name='Статус Замовлення'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='phone_image',
            field=models.ImageField(blank=True, null=True, upload_to='phone_images/%Y/%mm/%d', verbose_name='Головне Зображення'),
        ),
    ]
