# Generated by Django 5.0.1 on 2024-01-24 21:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_phonemodel_phone_additional_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='phone_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Опис'),
        ),
    ]
