# Generated by Django 5.0.1 on 2024-01-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_alter_phonemodel_phone_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Посилання')),
                ('page_status', models.BooleanField(default=True)),
            ],
        ),
    ]
