# Generated by Django 5.0.1 on 2024-01-26 20:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='page_content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Вміст сайту'),
        ),
        migrations.AddField(
            model_name='pages',
            name='page_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CEO'),
        ),
        migrations.AddField(
            model_name='pages',
            name='page_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Назва сторінки'),
        ),
    ]
