# Generated by Django 5.0.1 on 2024-02-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_pages_page_content_pages_page_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCategoryModel',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Бренд')),
                ('cat_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Посилання')),
            ],
            options={
                'verbose_name': 'Категорії',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'Сторінки', 'verbose_name_plural': 'Сторінки'},
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='phone_cat_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='page_status',
            field=models.BooleanField(default=True, verbose_name='Відображення сторінки'),
        ),
    ]
