# Generated by Django 5.0.1 on 2024-02-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0011_billings_billing_image_alter_pages_page_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billings',
            name='billing_image',
        ),
    ]
